name: monitoramento-nodejs-infra
services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    command: start --uri file:./etc/flagd/simulation.flagd.json
    volumes:
      - ./flags:/etc/flagd
    ports:
      - 8013:8013
      - 8015:8015
  postgres:
    build: ./.docker/postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
    volumes:
      - './.docker/postgres/:/docker-entrypoint-initdb.d/'
      - postgres_data:/var/lib/postgresql/data
    cap_add:
      - NET_ADMIN
    post_start:
      - command: tc qdisc add dev eth0 root netem delay 40ms 20ms distribution normal
        user: root
        privileged: true
  otel-lgtm:
    image: grafana/otel-lgtm:0.8.5
    volumes:
      - grafana_data:/data/grafana
      - prometheus_data:/data/prometheus
      - loki_data:/data/loki
      - ./.docker/otel-lgtm/grafana/custom-datasources.yml:/otel-lgtm/grafana/conf/provisioning/datasources/custom-datasources.yml
    environment:
      - GF_PATHS_DATA=/data/grafana
      - GF_PLUGINS_PREINSTALL=redis-datasource,grafana-postgresql-datasource
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  loki_data:
